server:
  port: 8080

spring:
  application:
    name: lms
  datasource:
    url: jdbc:postgresql://192.168.5.58:5432/lms
    username: postgres
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

minio:
  endpoint: http://localhost:9000
  accessKey: 0CleDaNWAViv2oNrDK0S
  secretKey: 4CKspL0EIBFdAPssfNswwLLwvUHnYo7nghd4BBwB
  bucket: library-assets

# 理想情况下，HS512秘密是512个随机位(64个随机字节)
# OpenSSL生成129个字节的秘密(172* 6) /8。
# openssl rand -base64 172 | tr -d '\n'
jwt:
  secret: EKLUF4cU6FuytxSFpddH86/+YptlWf9vHBuWcg==MsPJfkUBpd25DCKvmCusPLAl

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %magenta([%X{traceId}]) %green(%-5level) %cyan(%logger{36}) : %msg%n"
#  level:
#    org:
#      springframework: debug

google:
  books:
    api:
      key: ${google.books.api.key.origin}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

proxy:
  host: localhost
  port: 10808