server:
  port: 8080

spring:
  application:
    name: lms
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect