services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './PostgreSQL/postgresql_data:/bitnami/postgresql'
    environment:
      -  POSTGRES_USER=postgres # 默认用户名
      -  POSTGRESQL_PASSWORD=123456
  minio:
    image: minio/minio
    restart: always
    ports:
      - '9000:9000'  # API端口
      - '9001:9001'  # 控制台端口
    volumes:
      - './MinIO/data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - library-network
networks:
  library-network:
    driver: bridge